# defaults file for verapdf.logius
---
# Single entry for gmail address
# Application config
logius_install_dest: "/var/lib"
logius_git_url: "https://github.com/veraPDF/verapdf-crawler.git"
logius_git_root: "/vagrant"
logius_git_branch: "integration"
logius_git_update: no

logius_app_name: "logius"
logius_server_name: "localhost"

logius_linux_group: "{{ logius_app_name }}"
logius_linux_user: "{{ logius_app_name }}"

logius_app_home: "{{ logius_install_dest }}/{{ logius_app_name }}"
logius_app_bin: "{{ logius_app_home }}/bin"
logius_app_lib: "{{ logius_app_home }}/lib"
logius_app_conf: "{{ logius_app_home }}/conf"
logius_app_res: "{{ logius_app_home }}/res"
logius_log_dir: "/var/log/{{ logius_app_name }}"

tmp_download: "/tmp"
tanuki_wrapper_type: "linux-x86-64"
tanuki_wrapper_version: "3.5.33"
tanuki_wrapper_url: "https://wrapper.tanukisoftware.com/download/{{ tanuki_wrapper_version }}/wrapper-{{ tanuki_wrapper_type }}-{{ tanuki_wrapper_version }}.tar.gz"
tanuki_installer_dir: "{{ tmp_download }}/wrapper-{{ tanuki_wrapper_type }}-{{ tanuki_wrapper_version }}"

vera_app_details:
  logius-web:
    app_name: "logius-web"
    long_app_name: "Logius Web"
    app_description: "Logius web crawler application."
    main_class: "org.verapdf.crawler.LogiusWebApplication"
    required_start: ""
    required_stop: "verapdf-service"
  logius-sample:
    app_name: "logius-sample"
    long_app_name: "Logius Sample"
    app_description: "Logius sample application."
    main_class: "org.verapdf.crawler.core.Sample"
    required_start: ""
    required_stop: ""
  verapdf-service:
    app_name: "verapdf-service"
    long_app_name: "veraPDF Service"
    app_description: "Logius veraPDF REST services."
    main_class: "org.verapdf.service.VerapdfServiceApp"
    required_start: "logius-web"
    required_stop: ""

# Database admin password, this is fine for development machine config.
# Don't check your production password into a public Git repo.
logius_db_admin_password: vagrant
# Application database schema name
logius_db_schema_name: "{{ logius_app_name }}"
# Application database user
logius_db_user_name: "{{ logius_app_name }}"
# Application database password
logius_db_password: vagrant
# Database host
logius_db_host: localhost
# Database port
logius_db_port: 3306
# Derived connection string
logius_db_connection_string: "jdbc:mysql://{{ logius_db_host }}:{{ logius_db_port }}/{{ logius_db_schema_name }}?useSSL=false&autoReconnect=true"
# If need to run create schema scripts. Note that re-running them will purge the data
logius_db_create_schema: true
# Connection type (http | https)
logius_web_connection_type: http
# Web application port
logius_web_port: 9000
# Web application admin port
logius_web_admin_port: 9001
# veraPPDF service port
logius_verapdf_port: 8100
# veraPPDF service admin port
logius_verapdf_admin_port: 8101
# Sample Web application port
logius_samp_port: 8081
# Web sample application admin port
logius_samp_admin_port: 8082

logius_heritrix_home: "/opt/heritrix-3.2.0"
logius_heritrix_port: 8443
# Connection type (http | https)
logius_heritrix_connection_type: https
logius_heritrix_url: "{{ logius_heritrix_connection_type }}://{{ logius_server_name }}:{{ logius_heritrix_port }}/"
logius_heritrix_admin_user: admin
logius_heritrix_admin_password: logius
logius_verapdf_service_url: "{{ logius_web_connection_type }}://{{ logius_server_name }}:{{ logius_verapdf_port }}/"

logius_gmail_notification_account: logiuscrawlernotifier@gmail.com
logius_gmail_host: smtp.gmail.com
logius_gmail_address: "{{ logius_gmail_notification_account }}"
logius_gmail_user: "{{ logius_gmail_notification_account }}"
logius_gmail_password: Logius2017
logius_gmail_port: 587

logius_verapdf_path: "{{ verapdf_install_dest }}/verapdf"

logius_temp_folder: PLACEHOLDER_FOR_TEMP_FOLDER

logius_notifications_emails: maksim.bezrukov@duallab.com,yuliya.ivaniukovich@duallab.com,boris.doubrov@duallab.com
